events {}

http {
    upstream api_backend {
        server api1:8000;
        server api2:8000;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://api_backend;
        }
    }
}
